appUrl=https://appdev.askmitoto.com/
username=qaverve@gmail.com
password=Login12*

sourceName=AlokTest
host:192.168.1.157
user:view_u
dbpassword:u)9Urb0EwiqB9bZo
database:askmitoto_dev

#Verify Test Connection Message
testConnectionMsg=Test Connection Successful!

#Verify Success Message
sucessMessage=Data Source created successfully.

#Verify Data source status
data_Source_Status=Completed

#Max limit for click the refresh
maxAttempts=10

#Question for the data source
askQuestion=Give me all the user list